### PR TITLE
Upgrade example to dash v2.5.1

### PR DESCRIPTION
**Pull request by fbardos**
- Removed parameter routes_pathname_prefix during init of dash.Dash()
- Changed imports of dash.dcc and dcc.html
- Tested with shinyproxy v2.6.1.

I'm currently working on a Plotly Dash (v2.5.1) application and want to deploy it with shinyproxy (v2.6.1).
Therefore, I want to share my solution with you. Feel free to update the demo app if you find my solution useful.

Below are the steps, I ran thorugh:
I cloned this repository and tried to build the docker image with `sudo docker build -t openanalytics/shinyproxy-dash-demo .`

When trying to start a container from this builded image with shinyproxy, I get the following error:
```bash
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    import dash
  File "/usr/local/lib/python3.8/dist-packages/dash/__init__.py", line 5, in <module>
    from .dash import Dash, no_update  # noqa: F401,E402
  File "/usr/local/lib/python3.8/dist-packages/dash/dash.py", line 22, in <module>
    from werkzeug.debug.tbtools import get_current_traceback
ImportError: cannot import name 'get_current_traceback' from 'werkzeug.debug.tbtools' (/usr/local/lib/python3.8/dist-packages/werkzeug/debug/tbtools.py)
```

This led me to the fix in dash version 2.3.1 see [release notes](https://github.com/plotly/dash/releases/tag/v2.3.1).
After upgrading dash dependancy in `Dockerfile` from `dash=1.19.0` to `dash=2.5.1`, the following error occurs during container startup:
```bash
app.py:4: UserWarning:
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
app.py:5: UserWarning:
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html
Traceback (most recent call last):
  File "app.py", line 50, in <module>
    app.config.update({
  File "/usr/local/lib/python3.8/dist-packages/dash/_utils.py", line 114, in update
    self[k] = v
  File "/usr/local/lib/python3.8/dist-packages/dash/_utils.py", line 103, in __setitem__
    raise AttributeError(self._read_only[key], key)
AttributeError: ('Read-only: can only be set in the Dash constructor or during init_app()', 'routes_pathname_prefix')
```

So, I changed `app.py` by calling `dash.Dash()` without setting `routes_pathname_prefix`.

### CODE REVIEW

**Comment by alex817** [comment]
Thanks for creating the PR. This PR saved me a lot of time.

**Comment by djhurio** [comment]
Thanks a lot for the PR. I managed to spin-up the dash-demo thanks to this PR. I hope someone will merge this into the `master` as the current dash-demo from the `master` is not working anymore.

**Comment by LEDfan** [comment]
Thanks a lot, works perfectly!
